#ifndef SPURS_TASK_RENDER_RENDER_TAG_H
#define SPURS_TASK_RENDER_RENDER_TAG_H

enum{
	TAG_FOR_INPUT_DATA = 0,
	TAG_FOR_DMA_CACHE,
	TAG_FOR_VERTEX_SHADER,
	TAG_FOR_FRAGMENT_SHADER,
	TAG_FOR_COMMAND_BUFFER,
	TAG_FOR_GPU_SYNC,
	
	TAG_FOR_OUTPUT_DATA = 31,
};

#endif // SPURS_TASK_RENDER_RENDER_TAG_H