/*   SCE CONFIDENTIAL                                       */
/*   PlayStation(R)3 Programmer Tool Runtime Library 400.001 */
/*   Copyright (C) 2006 Sony Computer Entertainment Inc.    */
/*   All Rights Reserved.                                   */

void main
(
	float4 color_in : COLOR,
	//float2 texcoord : TEXCOORD0, 
	out float4 color : COLOR

	//uniform sampler2D texture
)
{
	//color.argb = tex2D(texture, texcoord);	// not correct
	//color.abgr = color_in * saturate( tex2D(texture, texcoord));
	color = color_in;
}
