/* SCE CONFIDENTIAL
 * PlayStation(R)3 Programmer Tool Runtime Library 360.001
 *                Copyright (C) 2010 Sony Computer Entertainment Inc.
 *                                               All Rights Reserved.
 */

//----------------------------------------------
// Simple fragment shader
// generates a color for the fragment by sampling
// the diffuse texture
//----------------------------------------------

void main (float2             texCoord    : TEXCOORD0,  // Lerped diffuse texture coordinate
           
           uniform sampler2D  diffuseMap,               // Diffuse texture map
           
           out float4         oColor      : COLOR)      // Final fragment color
{
	// Compute fragment color
    oColor = tex2D (diffuseMap, texCoord);
}
