#   SCE CONFIDENTIAL                                      
#   PlayStation(R)3 Programmer Tool Runtime Library 400.001
#   Copyright (C) 2008 Sony Computer Entertainment Inc.   
#   All Rights Reserved.                                  

CELL_MK_DIR ?= $(CELL_SDK)/samples/mk
include $(CELL_MK_DIR)/sdk.makedef.mk

PPU_SRCS = malloc_replace.ppu.c user_malloc.c
PPU_TARGET = malloc_replace.ppu.elf

include $(CELL_MK_DIR)/sdk.target.mk


