/*   SCE CONFIDENTIAL                                       */
/*   PlayStation(R)3 Programmer Tool Runtime Library 400.001 */
/*   Copyright (C) 2006 Sony Computer Entertainment Inc.    */
/*   All Rights Reserved.                                   */

void main
(
	float4 tint        : COLOR,
	float2 texcoord	: TEXCOORD0,

	uniform sampler2D texture,

	out float4 color : COLOR
)
{
	color = tex2D(texture, texcoord) * tint;
	color.w = tint.w;

}
