/*   SCE CONFIDENTIAL                                       */
/*   PlayStation(R)3 Programmer Tool Runtime Library 400.001 */
/*   Copyright (C) 2006 Sony Computer Entertainment Inc.    */
/*   All Rights Reserved.                                   */

void main
(
	float4 position	: POSITION,
	float2 texcoord	: TEXCOORD0,
	float4 normal : TEXCOORD1,

    uniform float4x4 modelViewProj={1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f},
    uniform float4x4 modelView,

	out float4 oPosition : POSITION,
	out float2 oTexCoord    : TEXCOORD0,
	out float4 oNormal : TEXCOORD1
)
{
	oPosition = mul(modelViewProj, position);
	oTexCoord = texcoord;
	oNormal = mul(modelView, normal);
}
