/*   SCE CONFIDENTIAL                                       */
/*   PlayStation(R)3 Programmer Tool Runtime Library 400.001 */
/*   Copyright (C) 2006 Sony Computer Entertainment Inc.    */
/*   All Rights Reserved.                                   */

void main
(
	float4 position	: POSITION,
	float2 texcoord : TEXCOORD0,

    uniform float4x4 ModelMatrix,
    uniform float4x4 ViewProjMatrix,

	out float4 ePosition : POSITION,
	out float4 oPosition : TEXCOORD0,
	out float2 oTexcoord   : TEXCOORD1
)
{
	// transpose
	ViewProjMatrix = transpose(ViewProjMatrix);
	ModelMatrix = transpose(ModelMatrix);

	// clip space position
	ePosition = mul(mul(ViewProjMatrix, ModelMatrix), position);

	// bypass data to fragment shader
    oPosition   = position;
    oTexcoord   = texcoord;
}
